### ISSUE TITLE
Print preview looks different

### ISSUE THREAD

**Issue by Vishal0203** [cognitom/paper-css#27]
Hi,
I have a very simple page with 2 different background colours. However the print preview shows the page as plain white.

Here's my page
<img width="1632" alt="screen shot 2018-04-17 at 12 33 30 pm" src="https://user-images.githubusercontent.com/8856973/38853671-9d12a048-423b-11e8-9d05-b9155c2c08ce.png">

And here's my print preview
<img width="689" alt="screen shot 2018-04-17 at 12 34 22 pm" src="https://user-images.githubusercontent.com/8856973/38853731-bf690ee8-423b-11e8-9778-322b1a246e9d.png">

I'm using flex. is that causing problem?

**Comment by cognitom** [comment]
Could be. Do you have any example code?

**Comment by cognitom** [comment]
Oops, could you check your print setting?
As default, no background will be printed in Chrome.

**Comment by Vishal0203** [comment]
Hi @cognitom,

I enabled `Background graphics` option and everything seems good now. 
However, there's some white-space left at the bottom after it gets converted to pdf or previewed in print. any ideas about that? 

Please see the bottom of the image attached. 
<img width="1240" alt="screen shot 2018-04-19 at 3 20 34 pm" src="https://user-images.githubusercontent.com/8856973/38984832-6997ace4-43e5-11e8-867d-2cc88dbd0218.png">

**Comment by cognitom** [comment]
The actual paper size could be slightly different. It depends on your printer driver. You can change [this line](https://github.com/cognitom/paper-css/blob/master/paper.css#L14) like below:

```css
body.A4 .sheet { width: 210mm; height: 297mm }
```

But, it might cause unexpected page breaks. (That's why `height` is set to `296mm` as default)

So, I recommend you to keep enough margin arround which is needed for printers.

Or, how about adding one extra page after the last page? (with setting the background on `body`)
